# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-28 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editors',
            new_name='Editor',
        ),
    ]
