# Generated by Django 2.2.7 on 2020-01-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
    ]
